-- CreateEnum
CREATE TYPE "SubCategory" AS ENUM ('CHICKEN_INGREDIENTS', 'SAUCE_INGREDIENTS', 'VEGETABLE_INGREDIENTS', 'SEASONING_INGREDIENTS', 'OIL_INGREDIENTS', 'CLEANING_SUPPLIES', 'COOKING_SUPPLIES', 'PACKAGING_SUPPLIES', 'SAFETY_SUPPLIES', 'OFFICE_SUPPLIES', 'COOKING_MANUAL', 'CLEANING_MANUAL', 'SAFETY_MANUAL', 'CUSTOMER_SERVICE_MANUAL', 'EQUIPMENT_MANUAL', 'OTHER');

-- AlterTable
ALTER TABLE "ChecklistTemplate" ADD COLUMN     "subCategory" "SubCategory";
